import * as path from 'path'
import * as fs   from 'fs'

const repoRoot  = path.resolve( __dirname, '../..' )
const claudeDir = path.join( repoRoot, '_Claude' )

const SKIP_DIR_NAMES = new Set( [ 'node_modules', '.git', '.obsidian' ] )
// `\migration\` = the migration-tooling folder ( the generated migration-map + its drift log ) — these
// are OUTPUTS/scratch of the migration, never migration targets themselves.
const SKIP_PATH_SEGMENTS = [ '\\logs\\', '\\reports\\', '\\audits\\', '\\scratch\\', '\\migration\\' ]

// Working docs deliberately kept as .md and slated for deletion once the migration lands — they
// self-declare "Disposable" in their own frontmatter. Not migration targets; skip by basename.
const SKIP_BASENAMES = new Set( [ '2026-06-30_references-drift.md', '2026-06-30_references-migration-tracker.md' ] )

function walk( dir: string, out: string[] ): void {
	for ( const entry of fs.readdirSync( dir, { withFileTypes: true } ) ) {
		if ( SKIP_DIR_NAMES.has( entry.name ) ) continue
		const full = path.join( dir, entry.name )
		if ( entry.isDirectory() ) walk( full, out )
		else if ( entry.isFile() ) out.push( full )
	}
}

const allFiles: string[] = []
walk( claudeDir, allFiles )

const mdFiles = allFiles.filter( f => {
	if ( !f.toLowerCase().endsWith( '.md' ) ) return false
	if ( SKIP_PATH_SEGMENTS.some( seg => f.includes( seg ) ) ) return false
	if ( SKIP_BASENAMES.has( path.basename( f ) ) ) return false
	if ( /\\component-map\./.test( f ) ) return false
	if ( f.endsWith( '.verify-throwaway.md' ) ) return false
	return true
} )

// ── protocol validator report (already generated by validate-corpus.ts) ──
const protocolReportPath = path.join( claudeDir, 'audits', 'kcd-validate-report.json' )
const protocolReport = JSON.parse( fs.readFileSync( protocolReportPath, 'utf-8' ) )
const protocolByFile = new Map<string, any>()
for ( const r of protocolReport.rows ) protocolByFile.set( r.file, r )   // key: repo-relative, forward slashes

interface MergedRow {
	mdPath: string           // repo-relative
	htmlPath: string | null  // repo-relative, expected pairing
	htmlExists: boolean
	mdSize: number
	htmlSize: number | null
	sizeStatus: 'missing' | 'anomaly' | 'ok'
	sizeRatio: number | null
	protocolStatus: 'missing' | 'invalid' | 'valid' | 'not-checked'
	protocolErrorCodes: string[]
	protocolNote: string | null
}

const rows: MergedRow[] = []

for ( const mdFull of mdFiles ) {
	const mdRel = path.relative( repoRoot, mdFull ).replace( /\\/g, '/' )
	const dir   = path.dirname( mdFull )
	const base  = path.basename( mdFull )

	const isIndex = base === 'index.md'
	const htmlBase = isIndex ? 'nav-index.html' : base.replace( /\.md$/i, '.html' )
	const htmlFull = path.join( dir, htmlBase )
	const htmlRel  = path.relative( repoRoot, htmlFull ).replace( /\\/g, '/' )

	const mdSize = fs.statSync( mdFull ).size
	const htmlExists = fs.existsSync( htmlFull )

	let sizeStatus: MergedRow['sizeStatus'] = 'missing'
	let sizeRatio: number | null = null
	let htmlSize: number | null = null

	if ( htmlExists ) {
		htmlSize = fs.statSync( htmlFull ).size
		sizeRatio = Math.round( ( htmlSize / mdSize ) * 100 ) / 100
		const expectedMin = Math.max( mdSize * 1.2, 500 )
		const expectedMax = mdSize * 5
		sizeStatus = ( htmlSize < expectedMin || htmlSize > expectedMax ) ? 'anomaly' : 'ok'
	}

	let protocolStatus: MergedRow['protocolStatus'] = 'not-checked'
	let protocolErrorCodes: string[] = []
	let protocolNote: string | null = null

	if ( htmlExists ) {
		const pr = protocolByFile.get( htmlRel )
		if ( !pr ) { protocolStatus = 'not-checked'; protocolNote = 'html exists but was not in the protocol-validator scan' }
		else if ( pr.ok ) { protocolStatus = 'valid' }
		else {
			protocolStatus = 'invalid'
			protocolErrorCodes = pr.errorCodes
			protocolNote = pr.errors.map( ( e: any ) => `${ e.where }: ${ e.msg }` ).join( ' | ' )
		}
	} else {
		protocolStatus = 'missing'
	}

	rows.push( { mdPath: mdRel, htmlPath: htmlExists ? htmlRel : `${ path.relative( repoRoot, dir ).replace( /\\/g, '/' ) }/${ htmlBase }`, htmlExists, mdSize, htmlSize, sizeStatus, sizeRatio, protocolStatus, protocolErrorCodes, protocolNote } )
}

rows.sort( ( a, b ) => a.mdPath.localeCompare( b.mdPath ) )

const summary = {
	total: rows.length,
	htmlMissing: rows.filter( r => !r.htmlExists ).length,
	sizeAnomaly: rows.filter( r => r.htmlExists && r.sizeStatus === 'anomaly' ).length,
	sizeOk: rows.filter( r => r.htmlExists && r.sizeStatus === 'ok' ).length,
	protocolValid: rows.filter( r => r.protocolStatus === 'valid' ).length,
	protocolInvalid: rows.filter( r => r.protocolStatus === 'invalid' ).length,
	protocolNotChecked: rows.filter( r => r.protocolStatus === 'not-checked' ).length,
	cleanBothValidators: rows.filter( r => r.htmlExists && r.sizeStatus === 'ok' && r.protocolStatus === 'valid' ).length,
}

const outPath = path.join( claudeDir, 'audits', 'migration-status-merged.json' )
fs.writeFileSync( outPath, JSON.stringify( { summary, rows }, null, '\t' ), 'utf-8' )

console.log( 'MERGED MIGRATION STATUS' )
console.log( '========================' )
console.log( `Total .md files tracked:        ${ summary.total }` )
console.log( `Missing .html:                  ${ summary.htmlMissing }` )
console.log( `.html exists, size OK:          ${ summary.sizeOk }` )
console.log( `.html exists, size ANOMALY:     ${ summary.sizeAnomaly }` )
console.log( `Protocol-valid:                 ${ summary.protocolValid }` )
console.log( `Protocol-INVALID:               ${ summary.protocolInvalid }` )
console.log( `Protocol not-checked (gap):     ${ summary.protocolNotChecked }` )
console.log( `CLEAN on both validators:       ${ summary.cleanBothValidators }` )
console.log( `\nWritten to ${ path.relative( repoRoot, outPath ) }` )
